### ISSUE TITLE
Question : unable to find Gartner_nmers_ranking.txt

### ISSUE THREAD

**Issue by zhaoxiaofei** [bassanilab/NeoRanking#2]
Dear Dr Markus Müller,

I was able to successfully run the scripts until test_voting_classifier.sh.
However, afterwards, I ran into errors.
More specifically, one of the scripts requires the presence of the Gartner_nmers_ranking.txt file, but we don't know where is this file. 
Here is the trace of the runtime error:

```
bash -evx /mnt/d/code/NeoRanking/plot_figure_3.sh
...
eval $CMD
+ eval PYTHONPATH=/mnt/d/code/NeoRanking python3 Scripts/paper/PlotClassifierResults.py -fn Figure_3A -re 'LR_*_neopep_*test.txt' 'XGBoost_*_neopep_*test.txt' Voting_classifier_0.50_neopep_test.txt SimpleRanking_neopep_mixmhc_test.txt SimpleRanking_neopep_netmhc_test.txt -pt neopep -g '"{'\''TESLA'\'':'\''TESLA'\'','\''HiTIDE'\'':'\''HiTIDE'\'','\''NCI_test'\'':'\''NCI-test'\'','\''NCI_train'\'':'\''NCI-train'\''}"' -cln '"{0:'\''LR'\'',1:'\''XGBoost'\'',2:'\''Voting'\'',3:'\''MixMHC+RNA'\'',4:'\''NetMHC+RNA'\''}"' -a 0.02 -rot 75 -las 30 -tis 18 -les 15 -sr -ga -o '"MixMHC+RNA,NetMHC+RNA,Gartner' et 'al.,LR,XGBoost,Voting"' -ds NCI_test -plt topn_counts
PYTHONPATH=/mnt/d/code/NeoRanking python3 Scripts/paper/PlotClassifierResults.py -fn Figure_3A -re LR_*_neopep_*test.txt XGBoost_*_neopep_*test.txt Voting_classifier_0.50_neopep_test.txt SimpleRanking_neopep_mixmhc_test.txt SimpleRanking_neopep_netmhc_test.txt -pt neopep -g "{'TESLA':'TESLA','HiTIDE':'HiTIDE','NCI_test':'NCI-test','NCI_train':'NCI-train'}" -cln "{0:'LR',1:'XGBoost',2:'Voting',3:'MixMHC+RNA',4:'NetMHC+RNA'}" -a 0.02 -rot 75 -las 30 -tis 18 -les 15 -sr -ga -o "MixMHC+RNA,NetMHC+RNA,Gartner et al.,LR,XGBoost,Voting" -ds NCI_test -plt topn_counts
++ PYTHONPATH=/mnt/d/code/NeoRanking
++ python3 Scripts/paper/PlotClassifierResults.py -fn Figure_3A -re 'LR_*_neopep_*test.txt' 'XGBoost_*_neopep_*test.txt' Voting_classifier_0.50_neopep_test.txt SimpleRanking_neopep_mixmhc_test.txt SimpleRanking_neopep_netmhc_test.txt -pt neopep -g '{'\''TESLA'\'':'\''TESLA'\'','\''HiTIDE'\'':'\''HiTIDE'\'','\''NCI_test'\'':'\''NCI-test'\'','\''NCI_train'\'':'\''NCI-train'\''}' -cln '{0:'\''LR'\'',1:'\''XGBoost'\'',2:'\''Voting'\'',3:'\''MixMHC+RNA'\'',4:'\''NetMHC+RNA'\''}' -a 0.02 -rot 75 -las 30 -tis 18 -les 15 -sr -ga -o 'MixMHC+RNA,NetMHC+RNA,Gartner et al.,LR,XGBoost,Voting' -ds NCI_test -plt topn_counts
Traceback (most recent call last):
  File "Scripts/paper/PlotClassifierResults.py", line 16, in <module>
    from Classifier.ClassifierResultParser import ClassifierResults, SimpleRankingResults, GartnerResultsNeopep, \
  File "/mnt/d/code/NeoRanking/Classifier/ClassifierResultParser.py", line 260, in <module>
    class GartnerResultsMutation(ClassifierResults):
  File "/mnt/d/code/NeoRanking/Classifier/ClassifierResultParser.py", line 263, in GartnerResultsMutation
    gartner_ranks = pd.read_csv(gartner_res_file, sep=',', header=0, index_col=False)
  File "/home/zhaoxiaofei/miniconda3/envs/neoranking/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/zhaoxiaofei/miniconda3/envs/neoranking/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/zhaoxiaofei/miniconda3/envs/neoranking/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/zhaoxiaofei/miniconda3/envs/neoranking/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/zhaoxiaofei/miniconda3/envs/neoranking/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/d/code/NeoRanking_resource/data/Gartner_nmers_ranking.txt'
```

**Comment by bassanilab** [comment]
Dear zhaoxiaofei 
indeed the Gartner_nmers_ranking.txt file, which contains the ranks of the nmers (mutations) from the Gartner et al. paper for NCI_test, was missing. I added it to the code directory (Data/Gartner_nmers_ranking.txt) and changed the respective path in  GlobalParameters.py. 
Markus

**Comment by zhaoxiaofei** [comment]
Thank I got the files that I needed. 
BTW I refactored your code so that all random generators use a predfined set of seeds to ensure reproduciblity, the code ist at:
https://github.com/XuegongLab/NeoRanking/
